# General Settings
name: Alvaro Carril
job_title: econ research &amp; computer tools
email: acarril@princeton.edu
description: I'm a research assistant at the NBER, and will begin an Economics PhD at Princeton in the fall of 2018.
avatar: /assets/pics/acarril_profile.jpg
favicon: /assets/icon/analytics-trans.png
twitter_handler: alvcarril
analytics_code: UA-54241026-2
disqus: alvarocarril

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: 'http://twitter.com/alvcarril' }
-  { name: instagram, url: 'https://www.instagram.com/alvcarril/' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: '' }
-  { name: skype, url: '' }
-  { name: github, url: '' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Includes
include: ["_pages"]

# Outputting
permalink: /posts/:title
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

# Fixes (bundle exec error)
exclude: [vendor]

# Syntax highlighting
highlighter: rouge

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
#    css_class: 'highlight'
